services:
    php:
        build:
            context: .
            dockerfile: docker/php/Dockerfile.prod
            network: host
        container_name: php
        restart: unless-stopped
        working_dir: /var/www/html/backend
        volumes:
            - ./backend:/var/www/html/backend
            - /var/www/html/backend/vendor
        networks:
            - snydiagram_network
        depends_on:
            postgres:
                condition: service_healthy
            # mysql_test:
            #     condition: service_healthy
        environment:
            DB_HOST: postgres
            DB_PORT: 5432


    node:
        build:
            context: .
            dockerfile: docker/node/Dockerfile.prod
            network: host
        container_name: node
        volumes:
            - ./backend/public:/var/www/html/backend/public
        working_dir: /var/www/html/frontend
        networks:
            - snydiagram_network
        command: sh -c "npm run build"
        restart: no

    nginx:
        image: nginx:alpine
        container_name: nginx
        restart: unless-stopped
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./backend:/var/www/html/backend:ro
            - ./docker/nginx/certs:/etc/nginx/certs:ro
            - ./docker/nginx/nginx.prod.conf:/etc/nginx/conf.d/default.conf:ro
        depends_on:
            php:
                condition: service_started
            node:
                condition: service_completed_successfully
        networks:
            - snydiagram_network

    # mysql_test:
    #     image: mysql:8
    #     container_name: mysql_test
    #     restart: unless-stopped
    #     command: --innodb-buffer-pool-size=128M --innodb-redo-log-capacity=67108864 --max-connections=50
    #     environment:
    #         MYSQL_ROOT_PASSWORD: root
    #         MYSQL_DATABASE: sql_validation
    #         MYSQL_USER: validator
    #         MYSQL_PASSWORD: validator
    #     mem_limit: 512m
    #     healthcheck:
    #         test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "--silent"]
    #         interval: 5s
    #         timeout: 5s
    #         retries: 20
    #         start_period: 30s
    #     networks:
    #         - snydiagram_network

    postgres:
        image: postgres:15
        container_name: postgres
        restart: unless-stopped
        environment:
            POSTGRES_DB: ${DB_DATABASE}
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
        volumes:
            - pgdata:/var/lib/postgresql/data
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME}"]
            interval: 5s
            timeout: 5s
            retries: 10
        networks:
            - snydiagram_network

volumes:
    pgdata:

networks:
    snydiagram_network:
        driver: bridge
